### ISSUE TITLE
[Feature] - PRs about Text and TextInput

### ISSUE THREAD

**Issue by efstathiosntonas** [fabOnReact/react-native-improved#10]
Hi Fabrizio, thank you for this repo.

Here's a list of PRs around Text and TextInput that I managed to gather at that time.

https://github.com/reactwg/react-native-releases/discussions/83#discussioncomment-6428962  (the comment with the list is hidden so expand it)

Some PRs are really old, some might be addressed in other PRs, some could be really outdated but the issue they are trying to solve might be still there.

**Comment by fabOnReact** [comment]
I started reviewing those PRs. I merged:
- https://github.com/facebook/react-native/pull/29070
- https://github.com/facebook/react-native/pull/41770 (I believe it will fix https://github.com/facebook/react-native/pull/37271)
I will merge the remaining PRs in 1-2 weeks. Thanks a lot

**Comment by fabOnReact** [comment]
Thanks @efstathiosntonas for the feedback.

1) Many of those PRs are from Expensify. 
2) I reached the company and they told me that they will not use the library.
3) I don't plan to add more fixes/PRs in this project.

I will now complete the project (add support for latest version of react-native and new arch) and then start working on my next project react-native-patch. 

React Native Devs that want to patch react-native:
1) they fork react-native-patch
2) they implement the patch (for example PR #16 and #29)
3) run `yarn release`

The advantages:
- Building from source react-native takes a long time (for ex. expensify/app 30-40 min).
- Building from source requires additional setup. This library instead just requires npm install.
- It is not a fork of react-native. We are still using the react-native APIs like ReactEditText, but over-riding some of their methods implementation (see examples in PRs [#16](#16) and [#29](#29)). We can upgrade without much trouble and use the latest react-native APIs.
- We don't patch node_modules. There will be no merge conflict when upgrading.
- Can be used to build new APIs based on react-native APIs
- The project would include extra documentation on the ReactNative APIs. The project also has an educational purpose.
- It is easy to migrate to a separate library (for example, doing lean core for the TextInput component), as we already build the native APIs.

I will wait for the community to start using this project and then maybe invest more time in it, but for now I don't plan on adding more fixes.
