### ISSUE TITLE
[Feature] - Use `RichText` for `Text` improvements

### ISSUE THREAD

**Issue by ehsemloh** [fabOnReact/react-native-improved#26]
### Scope
text render (classic arch)

[WIP PR](https://github.com/ehsemloh/react-native/pull/1)

### Goal
Strong behavior and interface consistency between iOS and Android
Inevitable inconsistency documented explicitly
First-class support of inline elements (i.e., Image)

Stretch goal: long text + virtualization

### Steps
1. Duplicate `Text` to `RichText` (JS + iOS + Android) as is, duplicate examples
2. Incrementally apply changes listed but not limited in [https://github.com/fabOnReact/react-native-improved/issues/10](https://github.com/fabOnReact/react-native-improved/issues/10)
3. Target both latest release branches for application ready as well as `main` for potential eventual merge to upstream

**Comment by fabOnReact** [comment]
https://github.com/fabOnReact/react-native-improved/issues/10#issuecomment-1923040313
